openapi: 3.1.0
info:
    version: 1.0.0
    title: Contacts APP
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: Contacts application for saving contacts with authorization and authentication
tags:
    # теги, що ви будете використовувати
    - name: Contacts
      description: Operations about users.
    - name: Auth
      description: Auth operations.
    - name: Users
      description: Users operations.

servers:
    - url: http://localhost:3000
    - url: https://nodejs-hw-mongodb-dyf3.onrender.com/
paths:
    # тут будуть посилання на ендпоінти
    /contacts:
        get:
            $ref: ./swagger/paths/contacts/get.yaml
        post:
            $ref: ./swagger/paths/contacts/post.yaml
    /contacts/{contactId}:
        get:
            $ref: ./swagger/paths/contacts/{contactId}/get.yaml
        delete:
            $ref: ./swagger/paths/contacts/{contactId}/delete.yaml
        put:
            $ref: ./swagger/paths/contacts/{contactId}/put.yaml
        patch:
            $ref: ./swagger/paths/contacts/{contactId}/patch.yaml
    /auth/register:
        post:
            $ref: ./swagger/paths/auth/register/post.yaml
    /auth/login:
        post:
            $ref: ./swagger/paths/auth/login/post.yaml
    /auth/refresh:
        post:
            $ref: ./swagger/paths/auth/refresh/post.yaml
    /auth/send-reset-email:
        post:
            $ref: ./swagger/paths/auth/send-reset-email/post.yaml
    /auth/reset-pwd:
        post:
            $ref: ./swagger/paths/auth/reset-pwd/post.yaml
    /users:
        get:
            $ref: ./swagger/paths/users/get.yaml
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
